gems: [jekyll-paginate]

### Github settings
# These settings are automatically forced by github anyway,
# so I'm making them explicit here to avoid descrepancies
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax

# whitelist pagination plugin so it isn't blocked by safe mode
# the fact that the github-pages gem doesn't already do this is a bug
whitelist:
  - jekyll-paginate

### Site config
baseurl: "" 
url: "http://davidudelson.com/"
permalink: /blog/:year/:month/:day/:title/
# these variables are used by _includes/head.html to provide metadata about the site
locale: en_US
title: David Udelson
description: "David Udelson's Corner of the Internet" 
keywords: "David Udelson programming blog software engineering spacemacs vim
emacs uva competitive programming"

### Blog config
excerpt_separator: <!--more-->
about_short: Computer nerd, aikidoka, tubist, and japanophile. I will sometimes post articles here, and they will probably be mostly about software.
blog:
    title: Probably Mostly Software
    subtitle: "A code enthusiast's blog"

### Concact info
contact:
    # My email is not provided here, as that would defeat the purpose of obfuscation!
    linkedin: "https://www.linkedin.com/in/david-udelson-6aa323123"
    github: "https://github.com/dudelson/"
    twitter: "https://twitter.com/dudelson_/"
    telegram: "https://t.me/dudelson"

### Front Matter defaults
defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"

### Build settings
paginate: 5
paginate_path: "/blog/page:num/"
